import json
import uvicorn
from fastapi import FastAPI
from fastapi.responses import Response
from image_generator import ImageGenerator

app = FastAPI()


@app.get("/")
def hello():
    """ Main page of the app. """
    return "Hello World!"


@app.get("/predict",
    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses = {
        200: {
            "content": {"image/png": {}}
        }
    },
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response,
)
async def predict(input_text: str):
    """ Return JSON serializable output from the model """
    payload = {'input_text': input_text}
    # classifier = PythonPredictor("")
    # return classifier.predict(payload)
    image_gen = ImageGenerator()
    image = image_gen.predict()
    return Response(content=image, media_type="image/png")

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)